version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - flask1
      - flask2
    networks:
      - mynetwork

  flask1:
    build: ./flask-app
    container_name: flask1
    restart: always
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mydb
    depends_on:
      - mysql
    networks:
      - mynetwork

  flask2:
    build: ./flask-app
    container_name: flask2
    restart: always
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mydb
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:  # Define the network here to ensure it's recognized