version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8089:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./fix-permissions.sh:/usr/local/bin/fix-permissions.sh  # Mount the script
    command: ["sh", "/usr/local/bin/fix-permissions.sh"]  # Run the script
    depends_on:
      - app1
      - app2
    networks:
      - app_network

  app1:
    build: ./app
    container_name: app1
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - app_network

  app2:
    build: ./app
    container_name: app2
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
